steps:
  # DOCKERHUB
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['USERNAME', 'PASSWORD']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build -t erickfis/stock-scrapper code -f code/Dockerfile.prod']
    secretEnv: ['USERNAME']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push erickfis/stock-scrapper']
    secretEnv: ['USERNAME']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/docker-pass/versions/1
    env: 'PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/1
    env: 'USERNAME'
