steps:

  # Install dependencies
  - name: 'docker.io/erickfis/selenium_py3'
    dir: 'code/stock_scrapper'
    entrypoint: pip
    args: ["install", "-r", "requirements_test.txt", "--user"]

  # Run unit tests
  - name: 'docker.io/erickfis/selenium_py3'
    dir: 'code/stock_scrapper/'
    entrypoint: python
    args: ["-m", "tox"]
