# base image
FROM python:3.9-slim-buster

# install requirements
WORKDIR /home/stock_scrapper/
COPY stock_scrapper/requirements.txt .
RUN pip3 install -r requirements.txt

# cp app files
COPY stock_scrapper/src/ .

EXPOSE 80

# container startup cmd
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
