# base image
FROM erickfis/selenium_py3

# install requirements
WORKDIR /home/stock_scrapper/
COPY stock_scrapper/requirements.txt .
RUN pip3 install -r requirements.txt

# cp app files
COPY stock_scrapper/src/ .

EXPOSE 8000

COPY stock_scrapper/gunicorn-config.py .

ENV enviro=cloud

# container startup cmd
cmd gunicorn main:app -c gunicorn-config.py
